#!/usr/bin/env python3
"""Generates worlds/rca_arena.sdf from rca_sim's arena definition.

The obstacle field, the arena size and the robot start pose are taken from
``rca_sim.world.World.default_arena(seed)`` so that the Gazebo arena and the
lightweight kinematic arena are geometrically the same scene. The generated SDF
is checked in; regenerate it with:

    python3 src/rca_gazebo/scripts/gen_world.py --seed 7

Nothing here is evaluation ground truth: it is world geometry.
"""

import argparse
import os
import sys

HEADER = '''<?xml version="1.0" ?>
<!-- GENERATED by src/rca_gazebo/scripts/gen_world.py (seed={seed}) - do not edit by hand. -->
<sdf version="1.9">
  <world name="rca_arena">
    <physics name="default" type="ignored">
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>

    <gravity>0 0 -9.8</gravity>
    <scene>
      <ambient>0.6 0.6 0.6 1</ambient>
      <background>0.85 0.88 0.92 1</background>
    </scene>
    <light type="directional" name="sun">
      <pose>0 0 12 0 0 0</pose>
      <diffuse>1 1 1 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>0.4 0.3 -1</direction>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>40 40</size></plane></geometry>
        </collision>
        <visual name="visual">
          <geometry><plane><normal>0 0 1</normal><size>40 40</size></plane></geometry>
          <material><ambient>0.3 0.3 0.32 1</ambient><diffuse>0.35 0.35 0.38 1</diffuse></material>
        </visual>
      </link>
    </model>
'''

WALL = '''
    <model name="wall_{i}">
      <static>true</static>
      <pose>{x} {y} 0.75 0 0 {yaw}</pose>
      <link name="link">
        <collision name="collision">
          <geometry><box><size>{lx} 0.2 1.5</size></box></geometry>
        </collision>
        <visual name="visual">
          <geometry><box><size>{lx} 0.2 1.5</size></box></geometry>
          <material><ambient>0.8 0.8 0.85 1</ambient><diffuse>0.9 0.9 0.95 1</diffuse></material>
        </visual>
      </link>
    </model>
'''

OBSTACLE = '''
    <model name="obstacle_{i}">
      <static>true</static>
      <pose>{x:.3f} {y:.3f} 0.5 0 0 0</pose>
      <link name="link">
        <collision name="collision">
          <geometry><cylinder><radius>{r:.3f}</radius><length>1.0</length></cylinder></geometry>
        </collision>
        <visual name="visual">
          <geometry><cylinder><radius>{r:.3f}</radius><length>1.0</length></cylinder></geometry>
          <material><ambient>0.9 0.75 0.2 1</ambient><diffuse>1.0 0.85 0.25 1</diffuse></material>
        </visual>
      </link>
    </model>
'''

ROBOT = '''
    <model name="rca_bot">
      <pose>{rx:.3f} {ry:.3f} 0.12 0 0 {rth:.4f}</pose>
      <link name="base_link">
        <inertial>
          <mass>6.0</mass>
          <inertia><ixx>0.08</ixx><iyy>0.12</iyy><izz>0.15</izz><ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia>
        </inertial>
        <collision name="collision">
          <geometry><box><size>0.45 0.32 0.16</size></box></geometry>
        </collision>
        <visual name="visual">
          <geometry><box><size>0.45 0.32 0.16</size></box></geometry>
          <material><ambient>0.15 0.4 0.8 1</ambient><diffuse>0.2 0.5 0.95 1</diffuse></material>
        </visual>

        <sensor name="lidar" type="gpu_lidar">
          <topic>scan</topic>
          <update_rate>10</update_rate>
          <always_on>1</always_on>
          <pose>0.18 0 0.14 0 0 0</pose>
          <lidar>
            <scan>
              <horizontal>
                <samples>90</samples>
                <resolution>1</resolution>
                <min_angle>-1.5707963</min_angle>
                <max_angle>1.5707963</max_angle>
              </horizontal>
              <vertical><samples>1</samples><min_angle>0</min_angle><max_angle>0</max_angle></vertical>
            </scan>
            <range><min>0.12</min><max>15.0</max><resolution>0.01</resolution></range>
          </lidar>
        </sensor>

        <sensor name="camera" type="camera">
          <topic>camera/image</topic>
          <update_rate>5</update_rate>
          <always_on>1</always_on>
          <pose>0.2 0 0.16 0 0 0</pose>
          <camera>
            <horizontal_fov>1.2217</horizontal_fov>
            <image><width>64</width><height>48</height><format>R8G8B8</format></image>
            <clip><near>0.1</near><far>20.0</far></clip>
          </camera>
        </sensor>

        <sensor name="imu" type="imu">
          <topic>imu</topic>
          <update_rate>20</update_rate>
          <always_on>1</always_on>
        </sensor>
      </link>

      <link name="left_wheel">
        <pose relative_to="base_link">0.10 0.19 -0.02 -1.5707963 0 0</pose>
        <inertial><mass>0.6</mass>
          <inertia><ixx>0.002</ixx><iyy>0.002</iyy><izz>0.003</izz><ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia>
        </inertial>
        <collision name="collision"><geometry><cylinder><radius>0.1</radius><length>0.05</length></cylinder></geometry>
          <surface><friction><ode><mu>1.2</mu><mu2>1.2</mu2></ode></friction></surface>
        </collision>
        <visual name="visual"><geometry><cylinder><radius>0.1</radius><length>0.05</length></cylinder></geometry>
          <material><ambient>0.1 0.1 0.1 1</ambient><diffuse>0.15 0.15 0.15 1</diffuse></material>
        </visual>
      </link>

      <link name="right_wheel">
        <pose relative_to="base_link">0.10 -0.19 -0.02 -1.5707963 0 0</pose>
        <inertial><mass>0.6</mass>
          <inertia><ixx>0.002</ixx><iyy>0.002</iyy><izz>0.003</izz><ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia>
        </inertial>
        <collision name="collision"><geometry><cylinder><radius>0.1</radius><length>0.05</length></cylinder></geometry>
          <surface><friction><ode><mu>1.2</mu><mu2>1.2</mu2></ode></friction></surface>
        </collision>
        <visual name="visual"><geometry><cylinder><radius>0.1</radius><length>0.05</length></cylinder></geometry>
          <material><ambient>0.1 0.1 0.1 1</ambient><diffuse>0.15 0.15 0.15 1</diffuse></material>
        </visual>
      </link>

      <link name="caster">
        <pose relative_to="base_link">-0.16 0 -0.08 0 0 0</pose>
        <inertial><mass>0.2</mass>
          <inertia><ixx>0.0002</ixx><iyy>0.0002</iyy><izz>0.0002</izz><ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia>
        </inertial>
        <collision name="collision"><geometry><sphere><radius>0.04</radius></sphere></geometry>
          <surface><friction><ode><mu>0.05</mu><mu2>0.05</mu2></ode></friction></surface>
        </collision>
        <visual name="visual"><geometry><sphere><radius>0.04</radius></sphere></geometry></visual>
      </link>

      <joint name="left_wheel_joint" type="revolute">
        <parent>base_link</parent><child>left_wheel</child>
        <axis><xyz expressed_in="__model__">0 1 0</xyz><limit><lower>-1e16</lower><upper>1e16</upper></limit></axis>
      </joint>
      <joint name="right_wheel_joint" type="revolute">
        <parent>base_link</parent><child>right_wheel</child>
        <axis><xyz expressed_in="__model__">0 1 0</xyz><limit><lower>-1e16</lower><upper>1e16</upper></limit></axis>
      </joint>
      <joint name="caster_joint" type="ball">
        <parent>base_link</parent><child>caster</child>
      </joint>

      <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
        <left_joint>left_wheel_joint</left_joint>
        <right_joint>right_wheel_joint</right_joint>
        <wheel_separation>0.38</wheel_separation>
        <wheel_radius>0.1</wheel_radius>
        <max_linear_acceleration>1.0</max_linear_acceleration>
        <topic>/model/rca_bot/cmd_vel</topic>
        <odom_topic>/model/rca_bot/odometry</odom_topic>
        <tf_topic>/model/rca_bot/tf</tf_topic>
        <frame_id>odom</frame_id>
        <child_frame_id>base_link</child_frame_id>
        <odom_publish_frequency>20</odom_publish_frequency>
      </plugin>
    </model>
'''

FOOTER = '''
  </world>
</sdf>
'''


def build(seed: int, half: float = 10.0) -> str:
    from rca_sim.world import World
    w = World.default_arena(seed)
    out = [HEADER.format(seed=seed)]
    walls = [(0.0, half, 0.0), (0.0, -half, 0.0), (half, 0.0, 1.5707963), (-half, 0.0, 1.5707963)]
    for i, (x, y, yaw) in enumerate(walls):
        out.append(WALL.format(i=i, x=x, y=y, yaw=yaw, lx=2 * half))
    for i, ob in enumerate(w.obstacles):
        out.append(OBSTACLE.format(i=i, x=ob.x, y=ob.y, r=ob.r))
    out.append(ROBOT.format(rx=w.robot.x, ry=w.robot.y, rth=w.robot.theta))
    out.append(FOOTER)
    return ''.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--seed', type=int, default=7)
    ap.add_argument('--out', default=os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))), 'worlds', 'rca_arena.sdf'))
    a = ap.parse_args()
    sdf = build(a.seed)
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, 'w') as f:
        f.write(sdf)
    print(f'wrote {a.out} ({len(sdf)} bytes)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
